[package]
name = "orgatalk-discord-orgateams"
version = "0.4.0"
authors = ["Jochen Kupperschmidt"]
edition = "2021"
rust-version = "1.62.0"
description = "List orga teams on the OrgaTalk Discord server"
license = "MIT"
keywords = ["discord"]

[dependencies]
anyhow = "1.0"
clap = { version = "3.2.8", default-features = false, features = ["cargo", "derive", "std"] }
lazy_static = "1.4.0"
multimap = "0.8.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
tera = { version = "1.16.0", default-features = false }
toml = "0.5.9"
ureq = { version = "2.4.0", features = ["json"] }
